"""msg

Revision ID: 7e706be7f0c7
Revises: 1b31377067d4
Create Date: 2025-12-08 15:04:36.619623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e706be7f0c7'
down_revision = '1b31377067d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commande', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('prix_avancer', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('prix_total', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commande', schema=None) as batch_op:
        batch_op.drop_column('prix_total')
        batch_op.drop_column('prix_avancer')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
